version: "2.4"
services:
  mysql:
    image: mysql:5.6
    restart: on-failure
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ../webapp/node-mysql-crud-app/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./checkiftablexists.sh:/checkiftablexists.sh
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dpuser
      - MYSQL_PASSWORD=dppassed
      - MYSQL_DATABASE=dp
    healthcheck:
      test: ["CMD", "bash", "/checkiftablexists.sh" ,"dp", "players"]
      start_period: 30s
      interval: 5s
      timeout: 3s
      retries: 4
  webapp:
    image: dp_webapp
    restart: on-failure
    volumes:
      - ./data/webapp:/node-mysql-crud-app/public/assets/img
      - ./healthcheck.js:/healthcheck.js
    environment:
      - DB_URL=mysql://dpuser:dppassed@mysql/dp
    healthcheck:
      # test: ["CMD", "curl", "http://localhost/"]
      test: ["CMD", "node", "/healthcheck.js"]
      start_period: 10s
      interval: 2s
      timeout: 3s
      retries: 4
    depends_on:
      mysql:
        condition: service_healthy # or service_started
  nginx:
    image: nginx:1.17.3
    ports:
    - "80:80"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      webapp:
        condition: service_healthy

